### ISSUE TITLE
Prev/Next Button with no text prevents Choice buttons from appearing

### ISSUE THREAD

**Issue by goldenxp** [Kirilllive/tuesday-js#11]
In a scenario where global interface prev and next buttons are purely iconic with no text, an error occurs which prevents choice buttons from showing up.

To reproduce:
1. Make a new project. Add story block. Add a scene. 
2. Add a choice with one button. Preview. Observe a button named "button" is visible in the center.
3. Return to editor. Perform "Scene edit"
4. Go to interface buttons global and delete the text < and > . 
5. Assign a unique color to each button and observe circular buttons in the editor. 
6. Click "back" to exit scene edit and run the preview project. Observe same button named "button" is not visible.
7. Open DevTools and observe the error. 

```
Uncaught TypeError: e.matchAll is not a function
    at values_button (<anonymous>:1:29575)
    at creation_dialog (<anonymous>:1:22730)
    at creation_scene (<anonymous>:1:13402)
    at base_creation (<anonymous>:1:7009)
    at load_story (<anonymous>:1:676)
    at <anonymous>:1:1574
    at play_novel (tuesday_visual.html:1303)
    at HTMLTableCellElement.onclick (tuesday_visual.html:318)
```

**Comment by goldenxp** [comment]
Attaching json as txt file
[test.json.txt](https://github.com/Kirilllive/tuesday-js/files/6542786/test.json.txt)

**Comment by Kirilllive** [comment]
ok fixed
