### ISSUE TITLE
User Text Input

### ISSUE THREAD

**Issue by fsvieira** [Kirilllive/tuesday-js#16]
Hi, 

I was experimenting with tuesday js, and I am trying to figure out how to get player input, for example at the beginning of the game I would like to get player name (https://fsvieira.github.io/thecorporation/). 

Does this feature exists ? If not, is it possible to add it using the html js features, how?

Great project, I tried to check the code, but its a little bit confusing to me.

**Comment by Kirilllive** [comment]
Hello!
you can use the browser window.prompt() function, And set name to variable value at "story_json.parameters.user_name"

For this you need to add this JS code in button choice or scene
`let person = prompt("Please enter your name:","User Name");
story_json.parameters.variables.user_name=person;`

https://www.w3schools.com/js/tryit.asp?filename=tryjs_prompt

[example project "enter name"](https://github.com/Kirilllive/tuesday-js/blob/master/example/example_enter_name.json)
