### ISSUE TITLE
Small visual glitch after switching scenes through a button

### ISSUE THREAD

**Issue by jsmonzani** [Kirilllive/tuesday-js#17]
Scenario:
- Block 1 - Scene 1 : display a dialog (1)
- Block 1 - Scene 2 : make a new with a button that goes to a new block (block)
- Block 1 - Scene 1 : display a dialog (2)
Bug: just before transitioning ti dialog 2, dialog 1 is briefly displayed again.

Sample code attached

`{
	"parameters": {
		"text_panel": {
			"size": [
				"95%",
				"25%"
			],
			"color": "#efefff",
			"color_text": "#000",
			"indent_text": "8px",
			"indent_bottom": "32px",
			"size_text": "20px",
			"style": "border-radius:16px;",
			"dialog_speed": "10",
			"art": {
				"en": ""
			},
			"className": "",
			"position": [
				"0",
				"0",
				"0"
			],
			"font_family": "Arial"
		},
		"name_panel": {
			"size": [
				"222px",
				"48px"
			],
			"position": [
				"0",
				"0",
				"-48px",
				"0"
			],
			"indent_text": "8px",
			"size_text": "18px",
			"color_text": "#000",
			"align": [
				"flex-start",
				"center"
			],
			"art": {
				"en": ""
			},
			"className": "",
			"font_family": "",
			"color": ""
		},
		"title": {
			"en": "new novel"
		},
		"launch_story": "block_1",
		"key": {
			"next": "",
			"back": "",
			"save": "",
			"load": "",
			"full_screen": "",
			"launch_story": "",
			"load_autosave": ""
		},
		"languares": [
			"en"
		],
		"buttons": [
			{
				"name": "tue_back",
				"style": "border-radius:26px;",
				"position": [
					"2.5%",
					"0",
					"0",
					"32px"
				],
				"size": [
					"38px",
					"38px"
				],
				"color": "",
				"color_text": "#000",
				"size_text": "28px",
				"text": "<",
				"art": {
					"en": ""
				},
				"sound": {
					"en": ""
				},
				"hotspot": [
					"0%",
					"0%"
				]
			},
			{
				"name": "tue_next",
				"style": "border-radius:26px;",
				"position": [
					"0",
					"2.5%",
					"0",
					"32px"
				],
				"size": [
					"38px",
					"38px"
				],
				"color": "",
				"color_text": "#000",
				"size_text": "28px",
				"text": ">",
				"art": {
					"en": ""
				},
				"sound": {
					"en": ""
				},
				"hotspot": [
					"0%",
					"0%"
				]
			}
		],
		"style_file": "",
		"autosave": false,
		"font": "Arial",
		"font_size": "18px",
		"variables": {},
		"sounds": {},
		"characters": {},
		"plugins": []
	},
	"blocks": {
		"block_1": [
			"319px",
			"219.5px",
			"block",
			false
		],
		"block_2": [
			"698px",
			"287.5px",
			"block",
			false
		]
	},
	"block_1": [
		{
			"dialogs": [
				{
					"text": "Message 1 - This message is going to flash after clicking on the button, it's a bug"
				}
			]
		},
		{
			"dialogs": [
				{
					"choice": [
						{
							"go_to": "block_2",
							"position": [
								"19.93%",
								0,
								0,
								"42.52%"
							],
							"size": [
								0,
								null
							],
							"color": "#efefff",
							"color_text": "#000",
							"text": {
								"en": "Click me to go to the next block. There will be a flashing dialog in between (bug)"
							},
							"indent_text": "8px",
							"art": {
								"en": ""
							},
							"sound": {
								"en": ""
							},
							"hotspot": [
								"0%",
								"0%"
							]
						}
					]
				}
			]
		}
	],
	"block_2": [
		{
			"dialogs": [
				{
					"text": "2. done"
				}
			]
		}
	]
}`

**Comment by Kirilllive** [comment]
Hello! I fixed this problem in the new release 5
