### ISSUE TITLE
Uploaded Video is playing without the sound

### ISSUE THREAD

**Issue by vladobra** [Kirilllive/tuesday-js#18]
Hello,

When I use a video component, the video is playing but no sound in Chrome and in Firefox.

**Comment by Kirilllive** [comment]
Hello!

Playback of any media that includes audio is generally blocked if the playback is programmatically initiated in a tab which has not yet had any user interaction. 

https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide

**Comment by vladobra** [comment]
The autoplay of video content works fine in fact. The only problem I am experiencing is the lack of audio. But, thank you for the clarification. I will test it after invoking a user interaction. I can embed youtube video as a HTML code in the scene. Though I like a lot TuesdayJs native embeded video, especially, that I can navigate automatically to another slide once vide is over.

Thank you...

**Comment by vladobra** [comment]
Btw, I think we can close this one. The issue was on my side. There is a slider sound in video properties, it was set to 0. After all both audio and video works fine. Thank u!!

**Comment by vladobra** [comment]
Not an issue.
