### ISSUE TITLE
Importing text translation

### ISSUE THREAD

**Issue by vladobra** [Kirilllive/tuesday-js#21]
Is it possible to import a language-translation file? The export of the language-translation file is possible.

**Comment by Kirilllive** [comment]
![Screenshot 2022-11-23 at 15 45 32](https://user-images.githubusercontent.com/13263198/203551570-0e49bca3-2ab9-4a93-a2cb-992b5c9ba678.jpg)


Export to CSV and TSV is possible, and you can set separators between rows and columns.
There is currently no import feature

**Comment by vladobra** [comment]
Thank you!
