### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'resolutions')

### ISSUE THREAD

**Issue by drkl151** [Kirilllive/tuesday-js#22]
<img width="1121" alt="Снимок экрана 2023-11-06 в 15 56 53" src="https://github.com/Kirilllive/tuesday-js/assets/81778290/20c7b0b3-8623-42c4-b523-318956b4bbf0">

Hello, I am getting an error when trying to launch the preview screen. 
A couple of days ago everything was working, I didn’t change anything much, but the preview screen stopped working and gave the error Uncaught TypeError: Cannot read properties of undefined (reading 'resolutions'). Please tell me what could be the problem?

**Comment by Kirilllive** [comment]
Hello! I fixed the error with "resolutions", but I think this is not the problem, can you show what is in the "Add-on" section?

![_Users_odin-interactive_Documents_Tuesday%20JS_tuesday_visual html](https://github.com/Kirilllive/tuesday-js/assets/13263198/7e405bcd-f6fe-4ee2-a1cc-290f4a31d01f)

**Comment by drkl151** [comment]
<img width="438" alt="Снимок экрана 2023-11-06 в 18 05 04" src="https://github.com/Kirilllive/tuesday-js/assets/81778290/9ae75ffd-47b9-4d84-98c8-89797dbb6e65">

Yes of course, here's my addition

**Comment by Kirilllive** [comment]
I tried to recreate your project, but I couldn't reproduce the error.
<img width="1440" alt="Screenshot 2023-11-06 at 19 44 51" src="https://github.com/Kirilllive/tuesday-js/assets/13263198/da36f590-e0f8-4d9b-bdb9-95f546ea8d64">

I can assume from the mention of blob in the screenshot that there is a problem in one of the project files (the problem may be in the file name).
You can send the JSON project file to tuesdayjsengine@gmail.com for a more precise definition of the problem?

**Comment by drkl151** [comment]
I sent a json file, I will be very grateful if you can help me figure out the error)

**Comment by Kirilllive** [comment]
You really have a problem with the file names. You need to change the file names for the sounds from 1, 2, 3 to longer ones, I recommend using only latin characters for file names for maximum compatibility.

<img width="1440" alt="Screenshot 2023-11-06 at 20 12 36" src="https://github.com/Kirilllive/tuesday-js/assets/13263198/46d4de44-7746-4e82-baf7-c9216ec39e60">

To prevent the error with "resolutions" from happening again, you need to specify the screen size

<img width="1440" alt="Screenshot 2023-11-06 at 20 16 53" src="https://github.com/Kirilllive/tuesday-js/assets/13263198/ca77d091-9db5-4a1c-9b6d-0f9b0b06555a">

**Comment by drkl151** [comment]
This helped a lot, thanks!
