### ISSUE TITLE
request: make the layout work on smartphones

### ISSUE THREAD

**Issue by blurymind** [Kirilllive/tuesday-js#9]
This is what it looks like on a smartphone

![image](https://user-images.githubusercontent.com/6495061/117862621-c4af8400-b28a-11eb-84ab-b0fd841a8ee2.png)

its unusable as the text is too tiny :)

**Comment by Kirilllive** [comment]
Wow Cool !!! 
Unfortunately, this is not the only problem with mobile devices, so they are not supported at the moment.

**Comment by blurymind** [comment]
The way styles are applied seems very tricky to change them. I was expecting to find a css file inthe src 😃 

What other problems are there on mobile? Mouse events?

**Comment by Kirilllive** [comment]
I haven't seen such a size problem on physical devices, otherwise it can be fixed in the meta viewport parameters.

The main problem is loading project files into the editor, at the moment the webkitdirectory method is used there which as practice has shown does not work correctly on mobile devices. This is the fault of the file managers, which do not allow sending only the directory to the browser.

**Comment by blurymind** [comment]
I found that Google has the filesystem api that sort of allows you to put them on a virtual folder , but it only works on chrome and recently broke in chromium.

Another way is to save the files as datauri strings. Its not the prettiest to pack them into the json file, but it gets it done and works across browsers 

There is also the new file access api, but that only works on desktop atm.

**Comment by Kirilllive** [comment]
We have our own cloud storage, which partially solves the problem. 

[https://tuesday.wantasoul.com/site/about](https://tuesday.wantasoul.com/site/about)

[https://kirill-live.itch.io/tuesday-js/devlog/237280/tuesdayjs-cloud-storage](https://kirill-live.itch.io/tuesday-js/devlog/237280/tuesdayjs-cloud-storage)

**Comment by blurymind** [comment]
i think the layout is the problem really. The web app is usable and works the same on desktop and mobile, but the layout atm cannot adapt to narrow screens at all and it is difficult to add that because tuesdayjs doesnt use css files. It appears like all styles are applied via javascript instead
